// <auto-generated />
namespace ASP.NET_RealEstateManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PropertyEstatemm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropertyEstatemm));
        
        string IMigrationMetadata.Id
        {
            get { return "202306090609293_Property-Estate-m-m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
