// <auto-generated />
namespace ASP.NET_RealEstateManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dataBaserebuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataBaserebuild));
        
        string IMigrationMetadata.Id
        {
            get { return "202306230149020_dataBase-rebuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
